apiVersion: v1
kind: namespace
metadata:
  name: flask-space


---
apiVersion: apps/v1
kind: deployment
metadata: 
  name: frontend
  namespace: flask-space
spac:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  tamplate:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: eldad86/flask-frontend:1.0.0
          ports: 
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: flask-space
spec: 
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetport: 5000
  type: LoadBalancer
